### PR TITLE
Install tests package_data only when tests are installed

### PR DESCRIPTION
**Pull request by Guillemdb**
Signed-off-by: Guillem Duran <guillem@sourced.tech>

### CODE REVIEW

**Comment by Guillemdb** [comment]
Following the suggestions from https://github.com/src-d/eee-commit-time-series/pull/14#discussion_r296197424 I updated the tests package_data to only be installed when installing the tests.

**Comment by zurk** [comment]
@Guillemdb CI is failed.

**Comment by vmarkovtsev** [comment]
@Guillemdb ping

**Comment by Guillemdb** [comment]
Fails because of the requirement-lint and pydocstyle thing. I will upload it once the CI from https://github.com/src-d/ml-core/pull/29  works.

**Comment by vmarkovtsev** [comment]
@Guillemdb time to rebase!

**Comment by vmarkovtsev** [comment]
@zurk We should release once this is merged.

**Pull request merged**
