### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by Guillemdb**
PR is based on https://github.com/src-d/ml-core/pull/3

This PR will contain the changes suggested by @vmarkovtsev in [https://github.com/src-d/ml-core/pull/1](https://github.com/src-d/ml-core/pull/1)

> 3. Add the old code. Pass CI.

### CODE REVIEW

**Comment by Guillemdb** [comment]
Konst made some changes to pass the tests:
- [Fix tensorflow test ](https://github.com/src-d/ml-core/pull/1/commits/9ecfbcbac5d5e42a0f0b8a5aacbc8f7c8edddb69)

**Comment by vmarkovtsev** [comment]
@Guillemdb Please rebase this on the latest changes in the other 2 PRs

**Comment by zurk** [comment]
ok, I updated comment that PR is based on https://github.com/src-d/ml-core/pull/3.
Let's deal with it first.

**Comment by zurk** [comment]
@Guillemdb please rebase and solve the conflict

**Pull request merged**
