### PR TITLE
Use bblfsh client v3.1.0

### PR DESCRIPTION
**Pull request by zurk**
duplicate of #31

### CODE REVIEW

**Comment by zurk** [comment]
@vmarkovtsev Travis is not triggered for some reason.

**Comment by vmarkovtsev** [comment]
I think it works: https://travis-ci.com/src-d/ml-core/pull_requests

Push .travis.ci changes separately?

**Comment by zurk** [comment]
ok, but at least I should remove Python 3.5 because it is unsupported by new bblfsh.

**Comment by vmarkovtsev** [comment]
cc @Guillemdb This is how the port should look like: only changing the imports and the tests stayed the same.

**Pull request merged**
